"""Constants for ISCE2 alos2App.py workflows."""

ALOS2APP_STEPS = [
    "preprocess",
    "baseline",
    "download_dem",
    "prep_slc",
    "slc_offset",
    "form_int",
    "swath_offset",
    "swath_mosaic",
    "frame_offset",
    "frame_mosaic",
    "rdr2geo",
    "geo2rdr",
    "rdrdem_offset",
    "rect_rgoffset",
    "diff_int",
    "look",
    "coherence",
    "ion_subband",
    "ion_unwrap",
    "ion_filt",
    "ion_correct",
    "filt",
    "unwrap",
    "geocode",
    "slc_mosaic",
    "slc_match",
    "dense_offset",
    "filt_offset",
    "geocode_offset",
]

ALOS2_LOOK_TABLE = {
    "SBS": {"look1": (2, 4), "look2": (4, 4), "look_ion": (16, 16)},
    "UBS": {"look1": (2, 3), "look2": (4, 4), "look_ion": (32, 32)},
    "UBD": {"look1": (2, 3), "look2": (4, 4), "look_ion": (32, 32)},
    "HBS": {"look1": (2, 4), "look2": (4, 4), "look_ion": (16, 16)},
    "HBD": {"look1": (2, 4), "look2": (4, 4), "look_ion": (16, 16)},
    "HBQ": {"look1": (2, 4), "look2": (4, 4), "look_ion": (16, 16)},
    "FBS": {"look1": (2, 4), "look2": (4, 4), "look_ion": (16, 16)},
    "FBD": {"look1": (2, 4), "look2": (4, 4), "look_ion": (16, 16)},
    "FBQ": {"look1": (2, 4), "look2": (4, 4), "look_ion": (16, 16)},
    "WBS": {"look1": (1, 14), "look2": (5, 2), "look_ion": (80, 32)},
    "WBD": {"look1": (1, 14), "look2": (5, 2), "look_ion": (80, 32)},
    "WWS": {"look1": (2, 14), "look2": (5, 2), "look_ion": (80, 32)},
    "WWD": {"look1": (2, 14), "look2": (5, 2), "look_ion": (80, 32)},
    "VBS": {"look1": (1, 14), "look2": (5, 2), "look_ion": (80, 32)},
    "VBD": {"look1": (1, 14), "look2": (5, 2), "look_ion": (80, 32)},
}
